version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run: npm install
      - run: npm run build
workflows:
  building-site:
    jobs:
      - build
