version: 2.1

jobs:
  install:   
    docker:
      - image: cimg/node:18.0
    steps:
      # Checkout the code as the first step.
      - checkout
      -run: npm install
      - run: npm run build

workflows:
  sample:
    jobs:
      - install