version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:18.0
    steps:
      # Checkout the code as the first step
      - checkout
      - run: npm install
  build:
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run: npm run build
workflows:
  sample:
    jobs:
      - install
      - build
          requires:
            - install
